version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/www/code-deploy-test/current
permissions:
  - object: /home/ubuntu/www/code-deploy-test/current
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    type:
      - file
  - object: /home/ubuntu/www/code-deploy-test/current
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    type:
      - directory

hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: scripts/application-stop.sh
      timeout: 300
      runas: ubuntu
